// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripAgency.Infrastructure.Context;

#nullable disable

namespace TripAgency.Infrastructure.Migrations
{
    [DbContext(typeof(TripAgencyDbContext))]
    [Migration("20250713040034_AddNotificationAndRefund")]
    partial class AddNotificationAndRefund
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripAgency.Data.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.BookingTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int")
                        .HasComment("Represents Booking status: 0 = Pending, 1 = Completed, 2 = Cancelled");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("PackageTripDateId")
                        .HasColumnType("int");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageTripDateId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingTrips", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.DestinationActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("DestinationId");

                    b.ToTable("DestinationActivities", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MidPriceForOneNight")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<int>("PackageTripDateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MinCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("PackageTrips", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndBookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndPackageTripDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PackageTripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartBookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartPackageTripDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageTripId");

                    b.ToTable("PackageTripDates", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("OrderDestination")
                        .HasColumnType("int");

                    b.Property<int>("PackageTripId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PackageTripId");

                    b.ToTable("PackageTripDestinations", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDestinationActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("OrderActivity")
                        .HasColumnType("int");

                    b.Property<int>("PackageTripDestinationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("PackageTripDestinationId");

                    b.ToTable("PackageTripDestinationActivities", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PackageTripId")
                        .HasColumnType("int");

                    b.Property<int>("TypeTripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageTripId");

                    b.HasIndex("TypeTripId");

                    b.ToTable("PackageTripTypes", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingTripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasComment("Represents Booking status: 0 = Pending, 1 = Completed, 2 = Cancelled");

                    b.HasKey("Id");

                    b.HasIndex("BookingTripId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingTripId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment(" status: 0 = Pending, 1 = Completed, 2 = Failed");

                    b.HasKey("Id");

                    b.HasIndex("BookingTripId")
                        .IsUnique();

                    b.ToTable("Refunds", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.TripDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TripId");

                    b.ToTable("TripDestinations", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.TypeTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TypeTrips", (string)null);
                });

            modelBuilder.Entity("TripAgency.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.BookingTrip", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.PackageTripDate", "PackageTripDate")
                        .WithMany("BookingTrips")
                        .HasForeignKey("PackageTripDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.User", "User")
                        .WithMany("BookingTrips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PackageTripDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Destination", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.City", "City")
                        .WithMany("Destinations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.DestinationActivity", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.Activity", "Activity")
                        .WithMany("DestinationActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.Destination", "Destination")
                        .WithMany("DestinationActivities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Hotel", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTrip", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.Trip", "Trip")
                        .WithMany("PackageTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDate", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.PackageTrip", "PackageTrip")
                        .WithMany("PackageTripDates")
                        .HasForeignKey("PackageTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PackageTrip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDestination", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.Destination", "Destination")
                        .WithMany("PackageTripDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.PackageTrip", "PackageTrip")
                        .WithMany("PackageTripDestinations")
                        .HasForeignKey("PackageTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("PackageTrip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDestinationActivity", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.Activity", "Activity")
                        .WithMany("PackageTripDestinationActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.PackageTripDestination", "PackageTripDestination")
                        .WithMany("PackageTripDestinationActivities")
                        .HasForeignKey("PackageTripDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("PackageTripDestination");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripType", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.PackageTrip", "PackageTrip")
                        .WithMany("PackageTripTypes")
                        .HasForeignKey("PackageTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.TypeTrip", "TypeTrip")
                        .WithMany("PackageTripTypes")
                        .HasForeignKey("TypeTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PackageTrip");

                    b.Navigation("TypeTrip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Payment", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.BookingTrip", "BookingTrip")
                        .WithOne("Payment")
                        .HasForeignKey("TripAgency.Data.Entities.Payment", "BookingTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingTrip");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Refund", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.BookingTrip", "BookingTrip")
                        .WithOne("Refund")
                        .HasForeignKey("TripAgency.Data.Entities.Refund", "BookingTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingTrip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.TripDestination", b =>
                {
                    b.HasOne("TripAgency.Data.Entities.Destination", "Destination")
                        .WithMany("TripDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripAgency.Data.Entities.Trip", "Trip")
                        .WithMany("TripDestinations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Activity", b =>
                {
                    b.Navigation("DestinationActivities");

                    b.Navigation("PackageTripDestinationActivities");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.BookingTrip", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Refund")
                        .IsRequired();
                });

            modelBuilder.Entity("TripAgency.Data.Entities.City", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Destination", b =>
                {
                    b.Navigation("DestinationActivities");

                    b.Navigation("PackageTripDestinations");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTrip", b =>
                {
                    b.Navigation("PackageTripDates");

                    b.Navigation("PackageTripDestinations");

                    b.Navigation("PackageTripTypes");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDate", b =>
                {
                    b.Navigation("BookingTrips");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.PackageTripDestination", b =>
                {
                    b.Navigation("PackageTripDestinationActivities");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.Trip", b =>
                {
                    b.Navigation("PackageTrips");

                    b.Navigation("TripDestinations");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.TypeTrip", b =>
                {
                    b.Navigation("PackageTripTypes");
                });

            modelBuilder.Entity("TripAgency.Data.Entities.User", b =>
                {
                    b.Navigation("BookingTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
